# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.allow import Allow  # noqa: E501
from openapi_client.rest import ApiException

class TestAllow(unittest.TestCase):
    """Allow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Allow
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.allow.Allow()  # noqa: E501
        if include_optional :
            return Allow(
                operation_statuses = [
                    {"status":"SUCCESS","successful":true}
                    ], 
                operation_types = [
                    'TRANSFER'
                    ], 
                errors = [
                    openapi_client.models.error.Error(
                        code = 12, 
                        message = 'Invalid account format', 
                        retriable = True, 
                        details = {"address":"0x1dcc4de8dec75d7aab85b567b6","error":"not base64"}, )
                    ], 
                historical_balance_lookup = True
            )
        else :
            return Allow(
                operation_statuses = [
                    {"status":"SUCCESS","successful":true}
                    ],
                operation_types = [
                    'TRANSFER'
                    ],
                errors = [
                    openapi_client.models.error.Error(
                        code = 12, 
                        message = 'Invalid account format', 
                        retriable = True, 
                        details = {"address":"0x1dcc4de8dec75d7aab85b567b6","error":"not base64"}, )
                    ],
                historical_balance_lookup = True,
        )

    def testAllow(self):
        """Test Allow"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
