# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.transaction_identifier_response import TransactionIdentifierResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestTransactionIdentifierResponse(unittest.TestCase):
    """TransactionIdentifierResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TransactionIdentifierResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.transaction_identifier_response.TransactionIdentifierResponse()  # noqa: E501
        if include_optional :
            return TransactionIdentifierResponse(
                transaction_identifier = openapi_client.models.transaction_identifier.TransactionIdentifier(
                    hash = '0x2f23fd8cca835af21f3ac375bac601f97ead75f2e79143bdf71fe2c4be043e8f', ), 
                metadata = None
            )
        else :
            return TransactionIdentifierResponse(
                transaction_identifier = openapi_client.models.transaction_identifier.TransactionIdentifier(
                    hash = '0x2f23fd8cca835af21f3ac375bac601f97ead75f2e79143bdf71fe2c4be043e8f', ),
        )

    def testTransactionIdentifierResponse(self):
        """Test TransactionIdentifierResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
