# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.sync_status import SyncStatus  # noqa: E501
from openapi_client.rest import ApiException

class TestSyncStatus(unittest.TestCase):
    """SyncStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SyncStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.sync_status.SyncStatus()  # noqa: E501
        if include_optional :
            return SyncStatus(
                current_index = 100, 
                target_index = 150, 
                stage = 'header sync'
            )
        else :
            return SyncStatus(
                current_index = 100,
        )

    def testSyncStatus(self):
        """Test SyncStatus"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
