# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.construction_derive_request import ConstructionDeriveRequest  # noqa: E501
from openapi_client.rest import ApiException

class TestConstructionDeriveRequest(unittest.TestCase):
    """ConstructionDeriveRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ConstructionDeriveRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.construction_derive_request.ConstructionDeriveRequest()  # noqa: E501
        if include_optional :
            return ConstructionDeriveRequest(
                network_identifier = openapi_client.models.network_identifier.NetworkIdentifier(
                    blockchain = 'bitcoin', 
                    network = 'mainnet', 
                    sub_network_identifier = openapi_client.models.sub_network_identifier.SubNetworkIdentifier(
                        network = 'shard 1', 
                        metadata = {"producer":"0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5"}, ), ), 
                public_key = openapi_client.models.public_key.PublicKey(
                    hex_bytes = '0', 
                    curve_type = 'secp256k1', ), 
                metadata = openapi_client.models.construction_derive_request_metadata.ConstructionDeriveRequest_metadata(
                    staking_credential = openapi_client.models.public_key.PublicKey(
                        hex_bytes = '0', 
                        curve_type = 'secp256k1', ), 
                    address_type = '0', )
            )
        else :
            return ConstructionDeriveRequest(
                network_identifier = openapi_client.models.network_identifier.NetworkIdentifier(
                    blockchain = 'bitcoin', 
                    network = 'mainnet', 
                    sub_network_identifier = openapi_client.models.sub_network_identifier.SubNetworkIdentifier(
                        network = 'shard 1', 
                        metadata = {"producer":"0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5"}, ), ),
                public_key = openapi_client.models.public_key.PublicKey(
                    hex_bytes = '0', 
                    curve_type = 'secp256k1', ),
        )

    def testConstructionDeriveRequest(self):
        """Test ConstructionDeriveRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
