# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.construction_api import ConstructionApi  # noqa: E501
from openapi_client.rest import ApiException


class TestConstructionApi(unittest.TestCase):
    """ConstructionApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.construction_api.ConstructionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_construction_combine(self):
        """Test case for construction_combine

        Create Network Transaction from Signatures  # noqa: E501
        """
        pass

    def test_construction_derive(self):
        """Test case for construction_derive

        Derive an AccountIdentifier from a PublicKey  # noqa: E501
        """
        pass

    def test_construction_hash(self):
        """Test case for construction_hash

        Get the Hash of a Signed Transaction  # noqa: E501
        """
        pass

    def test_construction_metadata(self):
        """Test case for construction_metadata

        Get Metadata for Transaction Construction  # noqa: E501
        """
        pass

    def test_construction_parse(self):
        """Test case for construction_parse

        Parse a Transaction  # noqa: E501
        """
        pass

    def test_construction_payloads(self):
        """Test case for construction_payloads

        Generate an Unsigned Transaction and Signing Payloads  # noqa: E501
        """
        pass

    def test_construction_preprocess(self):
        """Test case for construction_preprocess

        Create a Request to Fetch Metadata  # noqa: E501
        """
        pass

    def test_construction_submit(self):
        """Test case for construction_submit

        Submit a Signed Transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
