# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.amount import Amount  # noqa: E501
from openapi_client.rest import ApiException

class TestAmount(unittest.TestCase):
    """Amount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Amount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.amount.Amount()  # noqa: E501
        if include_optional :
            return Amount(
                value = '1238089899992', 
                currency = openapi_client.models.currency.Currency(
                    symbol = 'BTC', 
                    decimals = 8, 
                    metadata = {"Issuer":"Satoshi"}, ), 
                metadata = openapi_client.models.metadata.metadata()
            )
        else :
            return Amount(
                value = '1238089899992',
                currency = openapi_client.models.currency.Currency(
                    symbol = 'BTC', 
                    decimals = 8, 
                    metadata = {"Issuer":"Satoshi"}, ),
        )

    def testAmount(self):
        """Test Amount"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
