# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.network_api import NetworkApi  # noqa: E501
from openapi_client.rest import ApiException


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.network_api.NetworkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_network_list(self):
        """Test case for network_list

        Get List of Available Networks  # noqa: E501
        """
        pass

    def test_network_options(self):
        """Test case for network_options

        Get Network Options  # noqa: E501
        """
        pass

    def test_network_status(self):
        """Test case for network_status

        Get Network Status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
