# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class Coin(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'coin_identifier': 'CoinIdentifier',
        'amount': 'Amount'
    }

    attribute_map = {
        'coin_identifier': 'coin_identifier',
        'amount': 'amount'
    }

    def __init__(self, coin_identifier=None, amount=None, local_vars_configuration=None):  # noqa: E501
        """Coin - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._coin_identifier = None
        self._amount = None
        self.discriminator = None

        self.coin_identifier = coin_identifier
        self.amount = amount

    @property
    def coin_identifier(self):
        """Gets the coin_identifier of this Coin.  # noqa: E501


        :return: The coin_identifier of this Coin.  # noqa: E501
        :rtype: CoinIdentifier
        """
        return self._coin_identifier

    @coin_identifier.setter
    def coin_identifier(self, coin_identifier):
        """Sets the coin_identifier of this Coin.


        :param coin_identifier: The coin_identifier of this Coin.  # noqa: E501
        :type: CoinIdentifier
        """
        if self.local_vars_configuration.client_side_validation and coin_identifier is None:  # noqa: E501
            raise ValueError("Invalid value for `coin_identifier`, must not be `None`")  # noqa: E501

        self._coin_identifier = coin_identifier

    @property
    def amount(self):
        """Gets the amount of this Coin.  # noqa: E501


        :return: The amount of this Coin.  # noqa: E501
        :rtype: Amount
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Coin.


        :param amount: The amount of this Coin.  # noqa: E501
        :type: Amount
        """
        if self.local_vars_configuration.client_side_validation and amount is None:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Coin):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Coin):
            return True

        return self.to_dict() != other.to_dict()
