# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ConstructionMetadataRequestOptions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'relative_ttl': 'float',
        'transaction_size': 'float'
    }

    attribute_map = {
        'relative_ttl': 'relative_ttl',
        'transaction_size': 'transaction_size'
    }

    def __init__(self, relative_ttl=None, transaction_size=None, local_vars_configuration=None):  # noqa: E501
        """ConstructionMetadataRequestOptions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._relative_ttl = None
        self._transaction_size = None
        self.discriminator = None

        self.relative_ttl = relative_ttl
        self.transaction_size = transaction_size

    @property
    def relative_ttl(self):
        """Gets the relative_ttl of this ConstructionMetadataRequestOptions.  # noqa: E501


        :return: The relative_ttl of this ConstructionMetadataRequestOptions.  # noqa: E501
        :rtype: float
        """
        return self._relative_ttl

    @relative_ttl.setter
    def relative_ttl(self, relative_ttl):
        """Sets the relative_ttl of this ConstructionMetadataRequestOptions.


        :param relative_ttl: The relative_ttl of this ConstructionMetadataRequestOptions.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and relative_ttl is None:  # noqa: E501
            raise ValueError("Invalid value for `relative_ttl`, must not be `None`")  # noqa: E501

        self._relative_ttl = relative_ttl

    @property
    def transaction_size(self):
        """Gets the transaction_size of this ConstructionMetadataRequestOptions.  # noqa: E501


        :return: The transaction_size of this ConstructionMetadataRequestOptions.  # noqa: E501
        :rtype: float
        """
        return self._transaction_size

    @transaction_size.setter
    def transaction_size(self, transaction_size):
        """Sets the transaction_size of this ConstructionMetadataRequestOptions.


        :param transaction_size: The transaction_size of this ConstructionMetadataRequestOptions.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and transaction_size is None:  # noqa: E501
            raise ValueError("Invalid value for `transaction_size`, must not be `None`")  # noqa: E501

        self._transaction_size = transaction_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConstructionMetadataRequestOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConstructionMetadataRequestOptions):
            return True

        return self.to_dict() != other.to_dict()
