# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ConstructionMetadataResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'metadata': 'ConstructionMetadataResponseMetadata',
        'suggested_fee': 'list[Amount]'
    }

    attribute_map = {
        'metadata': 'metadata',
        'suggested_fee': 'suggested_fee'
    }

    def __init__(self, metadata=None, suggested_fee=None, local_vars_configuration=None):  # noqa: E501
        """ConstructionMetadataResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._metadata = None
        self._suggested_fee = None
        self.discriminator = None

        self.metadata = metadata
        if suggested_fee is not None:
            self.suggested_fee = suggested_fee

    @property
    def metadata(self):
        """Gets the metadata of this ConstructionMetadataResponse.  # noqa: E501


        :return: The metadata of this ConstructionMetadataResponse.  # noqa: E501
        :rtype: ConstructionMetadataResponseMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this ConstructionMetadataResponse.


        :param metadata: The metadata of this ConstructionMetadataResponse.  # noqa: E501
        :type: ConstructionMetadataResponseMetadata
        """
        if self.local_vars_configuration.client_side_validation and metadata is None:  # noqa: E501
            raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501

        self._metadata = metadata

    @property
    def suggested_fee(self):
        """Gets the suggested_fee of this ConstructionMetadataResponse.  # noqa: E501


        :return: The suggested_fee of this ConstructionMetadataResponse.  # noqa: E501
        :rtype: list[Amount]
        """
        return self._suggested_fee

    @suggested_fee.setter
    def suggested_fee(self, suggested_fee):
        """Sets the suggested_fee of this ConstructionMetadataResponse.


        :param suggested_fee: The suggested_fee of this ConstructionMetadataResponse.  # noqa: E501
        :type: list[Amount]
        """

        self._suggested_fee = suggested_fee

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConstructionMetadataResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConstructionMetadataResponse):
            return True

        return self.to_dict() != other.to_dict()
