# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ConstructionParseRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'network_identifier': 'NetworkIdentifier',
        'signed': 'bool',
        'transaction': 'str'
    }

    attribute_map = {
        'network_identifier': 'network_identifier',
        'signed': 'signed',
        'transaction': 'transaction'
    }

    def __init__(self, network_identifier=None, signed=None, transaction=None, local_vars_configuration=None):  # noqa: E501
        """ConstructionParseRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._network_identifier = None
        self._signed = None
        self._transaction = None
        self.discriminator = None

        self.network_identifier = network_identifier
        self.signed = signed
        self.transaction = transaction

    @property
    def network_identifier(self):
        """Gets the network_identifier of this ConstructionParseRequest.  # noqa: E501


        :return: The network_identifier of this ConstructionParseRequest.  # noqa: E501
        :rtype: NetworkIdentifier
        """
        return self._network_identifier

    @network_identifier.setter
    def network_identifier(self, network_identifier):
        """Sets the network_identifier of this ConstructionParseRequest.


        :param network_identifier: The network_identifier of this ConstructionParseRequest.  # noqa: E501
        :type: NetworkIdentifier
        """
        if self.local_vars_configuration.client_side_validation and network_identifier is None:  # noqa: E501
            raise ValueError("Invalid value for `network_identifier`, must not be `None`")  # noqa: E501

        self._network_identifier = network_identifier

    @property
    def signed(self):
        """Gets the signed of this ConstructionParseRequest.  # noqa: E501

        Signed is a boolean indicating whether the transaction is signed.  # noqa: E501

        :return: The signed of this ConstructionParseRequest.  # noqa: E501
        :rtype: bool
        """
        return self._signed

    @signed.setter
    def signed(self, signed):
        """Sets the signed of this ConstructionParseRequest.

        Signed is a boolean indicating whether the transaction is signed.  # noqa: E501

        :param signed: The signed of this ConstructionParseRequest.  # noqa: E501
        :type: bool
        """
        if self.local_vars_configuration.client_side_validation and signed is None:  # noqa: E501
            raise ValueError("Invalid value for `signed`, must not be `None`")  # noqa: E501

        self._signed = signed

    @property
    def transaction(self):
        """Gets the transaction of this ConstructionParseRequest.  # noqa: E501

        This must be either the unsigned transaction blob returned by `/construction/payloads` or the signed transaction blob returned by `/construction/combine`.  # noqa: E501

        :return: The transaction of this ConstructionParseRequest.  # noqa: E501
        :rtype: str
        """
        return self._transaction

    @transaction.setter
    def transaction(self, transaction):
        """Sets the transaction of this ConstructionParseRequest.

        This must be either the unsigned transaction blob returned by `/construction/payloads` or the signed transaction blob returned by `/construction/combine`.  # noqa: E501

        :param transaction: The transaction of this ConstructionParseRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and transaction is None:  # noqa: E501
            raise ValueError("Invalid value for `transaction`, must not be `None`")  # noqa: E501

        self._transaction = transaction

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConstructionParseRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConstructionParseRequest):
            return True

        return self.to_dict() != other.to_dict()
