# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ConstructionPreprocessResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'options': 'ConstructionPreprocessResponseOptions',
        'required_public_keys': 'list[AccountIdentifier]'
    }

    attribute_map = {
        'options': 'options',
        'required_public_keys': 'required_public_keys'
    }

    def __init__(self, options=None, required_public_keys=None, local_vars_configuration=None):  # noqa: E501
        """ConstructionPreprocessResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._options = None
        self._required_public_keys = None
        self.discriminator = None

        if options is not None:
            self.options = options
        if required_public_keys is not None:
            self.required_public_keys = required_public_keys

    @property
    def options(self):
        """Gets the options of this ConstructionPreprocessResponse.  # noqa: E501


        :return: The options of this ConstructionPreprocessResponse.  # noqa: E501
        :rtype: ConstructionPreprocessResponseOptions
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this ConstructionPreprocessResponse.


        :param options: The options of this ConstructionPreprocessResponse.  # noqa: E501
        :type: ConstructionPreprocessResponseOptions
        """

        self._options = options

    @property
    def required_public_keys(self):
        """Gets the required_public_keys of this ConstructionPreprocessResponse.  # noqa: E501


        :return: The required_public_keys of this ConstructionPreprocessResponse.  # noqa: E501
        :rtype: list[AccountIdentifier]
        """
        return self._required_public_keys

    @required_public_keys.setter
    def required_public_keys(self, required_public_keys):
        """Sets the required_public_keys of this ConstructionPreprocessResponse.


        :param required_public_keys: The required_public_keys of this ConstructionPreprocessResponse.  # noqa: E501
        :type: list[AccountIdentifier]
        """

        self._required_public_keys = required_public_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConstructionPreprocessResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConstructionPreprocessResponse):
            return True

        return self.to_dict() != other.to_dict()
