# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class MempoolResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'transaction_identifiers': 'list[TransactionIdentifier]'
    }

    attribute_map = {
        'transaction_identifiers': 'transaction_identifiers'
    }

    def __init__(self, transaction_identifiers=None, local_vars_configuration=None):  # noqa: E501
        """MempoolResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._transaction_identifiers = None
        self.discriminator = None

        self.transaction_identifiers = transaction_identifiers

    @property
    def transaction_identifiers(self):
        """Gets the transaction_identifiers of this MempoolResponse.  # noqa: E501


        :return: The transaction_identifiers of this MempoolResponse.  # noqa: E501
        :rtype: list[TransactionIdentifier]
        """
        return self._transaction_identifiers

    @transaction_identifiers.setter
    def transaction_identifiers(self, transaction_identifiers):
        """Sets the transaction_identifiers of this MempoolResponse.


        :param transaction_identifiers: The transaction_identifiers of this MempoolResponse.  # noqa: E501
        :type: list[TransactionIdentifier]
        """
        if self.local_vars_configuration.client_side_validation and transaction_identifiers is None:  # noqa: E501
            raise ValueError("Invalid value for `transaction_identifiers`, must not be `None`")  # noqa: E501

        self._transaction_identifiers = transaction_identifiers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MempoolResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MempoolResponse):
            return True

        return self.to_dict() != other.to_dict()
