# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    The version of the OpenAPI document: 1.4.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class TransactionIdentifierResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'transaction_identifier': 'TransactionIdentifier',
        'metadata': 'object'
    }

    attribute_map = {
        'transaction_identifier': 'transaction_identifier',
        'metadata': 'metadata'
    }

    def __init__(self, transaction_identifier=None, metadata=None, local_vars_configuration=None):  # noqa: E501
        """TransactionIdentifierResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._transaction_identifier = None
        self._metadata = None
        self.discriminator = None

        self.transaction_identifier = transaction_identifier
        if metadata is not None:
            self.metadata = metadata

    @property
    def transaction_identifier(self):
        """Gets the transaction_identifier of this TransactionIdentifierResponse.  # noqa: E501


        :return: The transaction_identifier of this TransactionIdentifierResponse.  # noqa: E501
        :rtype: TransactionIdentifier
        """
        return self._transaction_identifier

    @transaction_identifier.setter
    def transaction_identifier(self, transaction_identifier):
        """Sets the transaction_identifier of this TransactionIdentifierResponse.


        :param transaction_identifier: The transaction_identifier of this TransactionIdentifierResponse.  # noqa: E501
        :type: TransactionIdentifier
        """
        if self.local_vars_configuration.client_side_validation and transaction_identifier is None:  # noqa: E501
            raise ValueError("Invalid value for `transaction_identifier`, must not be `None`")  # noqa: E501

        self._transaction_identifier = transaction_identifier

    @property
    def metadata(self):
        """Gets the metadata of this TransactionIdentifierResponse.  # noqa: E501


        :return: The metadata of this TransactionIdentifierResponse.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this TransactionIdentifierResponse.


        :param metadata: The metadata of this TransactionIdentifierResponse.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransactionIdentifierResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TransactionIdentifierResponse):
            return True

        return self.to_dict() != other.to_dict()
